### ISSUE TITLE
Windows development barriers

### ISSUE THREAD

**Issue by aligneddev** [Azure-Samples/service-fabric-dotnet-core-getting-started#21]
The readme.md state "build.ps1 - PowerShell script to build source on Windows.". I can't find that file.

Also, I was expecting to see a Visual Studio Solution file with an .sfproj file. Maybe I just need to learn more about working outside of that environment?

**Comment by rapatchi** [comment]
Hi @aligneddev ,

Thanks for reporting this issue.  I shall checkin the the build.cmd so that we will be able to build the applications on windows.
Meanwhile you can unblock yourself by authoring a build.cmd similar to build.sh.

For dotnetcore applications you can use service fabric reliable services plugin on VSCode to manage applications. Documentation link: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-vs-code

**Comment by rapatchi** [comment]
This has been fixed now. Closing this issue. Thanks.
